### ISSUE TITLE
`<title>` contains a Raute

### ISSUE THREAD

**Issue by danieldiekmeier** [timomeh/timomeh.de#4]
**Description:**

When looking into the tab bar of my internet webbrowser, I was shocked to discover what we in Germany call a Raute: 

<img width="179" alt="image" src="https://user-images.githubusercontent.com/2098462/188415849-245ea526-503f-4609-95e8-b9d9cdefc826.png">

**Expected Behaviour:**

It shouldn't have a Raute.

**Comment by timomeh** [comment]
Thanks for noticing the shocking Raute. I hope you didn't confuse my page with Instagram. I removed the Raute in 1d538c3ea5e2c2175f711f8c007f8bbca94fceb9.

**Comment by danieldiekmeier** [comment]
Thanks for the Quick Turnaround!
